### ISSUE TITLE
Building docker container fails

### ISSUE THREAD

**Issue by lumpidu** [cadia-lvl/unit-selection-festival#4]
If I build the docker container as described via:

```
docker build . --tag lvl-us-is-run -f runtime.Dockerfile
```

then I get the following error:

```
....
Step 17/31 : WORKDIR /opt/ext
 ---> Using cache
 ---> ad0ad9f4fc83
Step 18/31 : COPY ext/*.mdl ipd_clean_slt2018.mdl
COPY failed: no source files were specified
```

Do I need to create some directories locally ?

**Comment by judyfong** [comment]
The runtime file only works if you have created the ext directory with the relevant ext files and have previously run the training dockerfile, both of which are mentioned in the readme. But this might need to be more more clear. Neither the voice data files nor the .mdl come with the repo.

**Comment by lumpidu** [comment]
Are these files freely available ?

**Comment by judyfong** [comment]
A .mdl is available at https://github.com/cadia-lvl/tts_data/blob/master/pron_data/ipd_clean_slt2018.mdl @thdg might be able to tell you how to get the talromur audio files.

**Comment by thdg** [comment]
@lumpidu the audio files are currently not available but will be in the future.

**Comment by thdg** [comment]
I have updated the README to make it a bit more clear about what is inside the repository, i.e. only a configuration for a voice but not a trained model.
